### PR TITLE
Minimal changes to get utils.ts working

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks! Tell me when you want to merge this, or if you want to keep hammering at it.

**Comment by JohanMabille** [comment]
I need to polish it a bit (especially for the exports), I'll ping you when it's done.

**Comment by JohanMabille** [comment]
@jasongrout I think this one is ready to go, I'll migrate other files in another PR so other developers can already get these changes. The changes in this PR are quite mechanical, however let me know if we can improve some pattern used here.

**Comment by jasongrout** [comment]
Great, thanks!

**Pull request merged**
